import React,{useEffect,useState} from 'react'
import {Badge,Button,Dialog,Field,GameCard,Progress,Resource,Segmented,Shape,Toggle} from './RetroUI.jsx'

export default function DesignSystem({onClose}) {
 const [theme,setTheme]=useState('light'),[reduced,setReduced]=useState(false),[dialog,setDialog]=useState(false),[toast,setToast]=useState(''),[claimed,setClaimed]=useState(false),[name,setName]=useState(''),[mode,setMode]=useState('quiet')
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(timer)},[toast])
 return <main className="pr-system pr-kit" data-pr-theme={theme} data-pr-motion={reduced?'reduced':'default'}>
  <header className="pr-kit-header"><strong>numquest / playground</strong><Segmented label="Tema preview" value={theme} onChange={setTheme} options={[{value:'light',label:'Light'},{value:'dark',label:'Dark'}]}/><Button variant="secondary" size="sm" onClick={onClose}>← Kembali ke aplikasi</Button></header>
  <section className="pr-kit-hero"><span className="pr-eyebrow">PLAYFUL RETRO GAME SYSTEM / v1.0</span><h1>Serius main.<br/>Bebas berekspresi.</h1><p>Fondasi yang konsisten. Komponen yang bisa dirakit. Karakter yang tumbuh dari warna, bentuk, dan interaksi.</p></section>
  <section className="pr-kit-section"><h2>01 / Warna & bentuk</h2><div className="pr-palette">{[['Green','--pr-green-400'],['Pink','--pr-pink-200'],['Lavender','--pr-lavender-200'],['Yellow','--pr-yellow-300'],['Mint','--pr-mint-100'],['Cream','--pr-cream-50']].map(([label,color])=><div className="pr-swatch" key={label} style={{background:`var(${color})`}}><span>{label}</span><span>{color.replace('--pr-','')}</span></div>)}</div><div className="pr-kit-row" style={{marginTop:24}}>{['clover','spark','arch','circle'].map(kind=><div className="pr-shape-demo" key={kind}><Shape kind={kind}/></div>)}<p>4px rhythm · 24px cards · pill actions · offset shadows</p></div></section>
  <section className="pr-kit-section"><h2>02 / Core UI</h2><div className="pr-kit-row"><Button onClick={()=>setToast('✓ Aksi utama diterima')}>Mulai main ↗</Button><Button variant="secondary" onClick={()=>setToast('Pilihan kedua dipilih')}>Pelajari dulu</Button><Button variant="tertiary" onClick={()=>setToast('Kembali ke pilihan')}>Kembali</Button><Button variant="danger" onClick={()=>setDialog(true)}>Keluar sesi</Button><Button disabled>Terkunci</Button><Button loading>Memuat</Button></div><div className="pr-kit-grid" style={{marginTop:24}}><GameCard title="Input & validasi" expression="quiet"><Field id="demo-name" label="Nama pemain" placeholder="Tulis namamu" value={name} onChange={e=>setName(e.target.value)} error={name.length>16?'Maksimal 16 karakter.':undefined}/></GameCard><GameCard title="Aksesibilitas" expression="quiet"><Toggle label="Kurangi gerakan" checked={reduced} onChange={setReduced}/><p>Fokus keyboard, target sentuh, serta status berbentuk teks.</p></GameCard><GameCard title="Expression"><Segmented label="Ekspresi komponen" value={mode} onChange={setMode} options={['quiet','playful','celebration'].map(value=>({value,label:value}))}/><div style={{marginTop:20}}><Button expression={mode} onClick={()=>setToast('✓ Pilihan tersimpan')}>Coba interaksi</Button></div></GameCard></div></section>
  <section className="pr-kit-section"><h2>03 / Game cards, progression & rewards</h2><div className="pr-kit-grid"><GameCard tone="pink" eyebrow="MISI HARI INI" title="Sedikit latihan. Banyak kemajuan." description="Selesaikan 5 soal dengan strategi pilihanmu." badge={<Badge>3 / 5</Badge>} footer={<Button onClick={()=>setToast('Demo: lanjutkan misi')}>Lanjutkan ↗</Button>}><Progress value={60} label="Progres misi demo"/></GameCard><GameCard tone="lavender" eyebrow="LEVEL 02" title="Lihat polanya." description="Perkalian adalah penjumlahan yang punya ritme." media={<Shape kind="clover"/>} footer={<Button variant="secondary" disabled>⌑ Terkunci · tuntaskan level 01</Button>}/><GameCard tone="yellow" expression={mode} eyebrow="HADIAH HARIAN" title={claimed?'Sudah diambil.':'Langkah kecilmu berharga.'} badge={<Badge tone="positive">{claimed?'✓ Diklaim':'★ Tersedia'}</Badge>} footer={<Button disabled={claimed} onClick={()=>{setClaimed(true);setToast('★ +50 koin demo. Saldo aplikasi tidak berubah.')}}>{claimed?'Diklaim':'Ambil hadiah'}</Button>}><Resource value="50" label="koin demo"/></GameCard></div></section>
  <section className="pr-kit-section"><h2>04 / Quiet HUD & feedback</h2><GameCard expression="quiet"><div className="pr-kit-row"><Resource symbol="♡" value="3" label="nyawa"/><Resource symbol="◷" value="01:32" label="waktu"/><Resource symbol="★" value="1.250" label="skor"/><Badge tone="positive">✓ Tepat</Badge><Badge tone="negative">! Coba strategi lain</Badge><Badge tone="warning">◷ 10 detik tersisa</Badge></div></GameCard></section>
  <section className="pr-kit-section"><h2>05 / Aturan perakitan</h2><div className="pr-kit-grid"><GameCard title="Quiet" description="Form, pengaturan, dan soal. Permukaan tenang; informasi yang utama."/><GameCard title="Playful" description="Home, level, dan misi. Satu bentuk besar dan satu warna aksen per kartu."/><GameCard title="Celebration" description="Hadiah dan pencapaian. Kontras kuat, bentuk ekspresif, lalu kembali tenang."/></div></section>
  <Dialog open={dialog} onClose={()=>setDialog(false)} title="Istirahat sebentar?"><p>Ini preview pola konfirmasi. Sesi latihanmu tidak berubah.</p><div className="pr-kit-row" style={{marginTop:24}}><Button onClick={()=>setDialog(false)}>Lanjutkan</Button><Button variant="secondary" onClick={()=>{setDialog(false);setToast('Demo sesi ditutup')}}>Keluar</Button></div></Dialog>
  {toast&&<div role="status" className="pr-toast">{toast}</div>}
 </main>
}
